### ISSUE TITLE
Release 0.2.0.0 / new maintainer wanted

### ISSUE THREAD

**Issue by andreasabel** [haskell-hvr/resolv#19]
@phadej: I'd like to release 0.2.0.0 now containing:
- at least #16 
- probably #12
- maybe #17 

Note that #16 shouldn't be a revision since it takes away building with GHC < 7.6.

For a couple of month now there is the question open whether you want to give me upload rights on Hackage or do the releases yourself.  Please give an answer, so we can move on with this package.

**Comment by phadej** [comment]
I removed myself from `resolv` maintainer group: https://hackage.haskell.org/package/resolv/maintainers/

Either ask herbert to add you there, or takeover the package.

**Comment by andreasabel** [comment]
> I removed myself from `resolv` maintainer group: [hackage.haskell.org/package/resolv/maintainers](https://hackage.haskell.org/package/resolv/maintainers/)

Not sure why this was necessary.  This needlessly complicates things. Sigh.

> Either ask herbert to add you there, or takeover the package.

You could as co-maintainer just have added me.  Herbert has gone into hiding.  Very funny!

**Comment by phadej** [comment]
> You could as co-maintainer just have added me

I was helping Herbert, I didn't ever "took over" the maintainership. I don't want to add more maintainers transitively as I weren't explicitly allowed to do so, and particularly because *we do disagree* on how stuff should be maintained.

This is easier to me, I feel bad for making things harder, but OTOH I would feel worse by doing something I'm not 100% happy with.

**Comment by andreasabel** [comment]
Since no shortcut is possible anymore, I suggest someone with domain knowledge takes over.

Alexey @lyokha, if you are interested in taking over this package, I'd second this.
The process is described here: https://wiki.haskell.org/Taking_over_a_package

**Comment by lyokha** [comment]
@andreasabel, I do not mind. So, should I make further steps, e.g. mailing to Herbert, or will you do it yourself?

**Comment by andreasabel** [comment]
@lyokha wrote:
> @andreasabel, I do not mind. So, should I make further steps, e.g. mailing to Herbert, or will you do it yourself?

Thanks, great!
Yes please email Herbert, and follow the steps of the package takeover.

**Comment by lyokha** [comment]
I mailed Herbert.

**Comment by lyokha** [comment]
@andreasabel , news at this moment is short: I sent mails to @hvr January 30 and then, 3 weeks later, February 20, to hackage-admin@haskell.org. Nobody responded so far.

**Comment by lyokha** [comment]
Good news! Herbert will look at this soon, probably, this week.

**Comment by lyokha** [comment]
@andreasabel, yesterday I got maintenance permissions to resolv at Hackage, but I am waiting Herbert as he wanted to have a look at the issues.

**Comment by ulysses4ever** [comment]
@lyokha could you in the meantime, please, bump `base` upper bound on the current Hackage release via a revision? That would unstuck some things...

**Comment by lyokha** [comment]
@ulysses4ever, done, now `base >= 4.5 && <5`

**Comment by lyokha** [comment]
@andreasabel I propose to go ahead as Herbert keeps silent. Further steps would be:

1. Merge #16, #12 (perhaps others, I cannot do this as I don't have permissions in this repository)
2. I would also consider merging #17 by @dminuoso after fixing a small issue (`throw` -> `throwIO`)
3. Bump upper base constraint to `5` in Cabal file (and those of other packages too if needed)
4. Build and make *sdist* and haddocks (I can do this in my branch after pulling from upstream or in a cloned upstream)
5. Upload built sdist (perhaps, haddocks too) on Hackage (I can do this as I have permission).

**Comment by lyokha** [comment]
3a. Update *Changelog.md*.

**Comment by andreasabel** [comment]
@lyokha : I invited you to this repository with write permission, so you can merge PRs now.
You should now also be able to comment on PRs (after accepting the invitation, of course).

I think it is best to keep the code for `resolv` here on `haskell-hvr` which is meant as a collaborative organization by Herbert (where we work together on maintaining packages).

If you make a candidate upload to hackage first and ping me, I can have a look at the candidate before you finally publish.
Usually, haddocks are built on Hackage for the final release, so it is better to not upload them manually there (unless build on Hackage fails).
However, for candidates one has to upload the documentation manually.

**Comment by andreasabel** [comment]
@lyokha: Would you add me as another maintainer on hackage so that I could act as co- or fall-back maintainer?  That would also enable me to upload candidate releases for testing purposes.
https://hackage.haskell.org/package/resolv/maintainers/

**Comment by lyokha** [comment]
Ok, in a 1 or 2 hour when i reach to my laptop, I would also wait #17 with improvements requested, when @dminuoso looks at it

**Comment by lyokha** [comment]
@andreasabel I added you

**Comment by andreasabel** [comment]
@lyokha : Do you want to take over the stackage maintainership? https://github.com/commercialhaskell/stackage/blob/99c752318f259be25cf13c1d994a50f2f0583829/MAINTAINERS.md#adding-a-package

Since `resolv` is already part of Stackage, it amounts to putting the following entry under a section with your name and email:
https://github.com/commercialhaskell/stackage/blob/99c752318f259be25cf13c1d994a50f2f0583829/build-constraints.yaml#L5342

You will then be notified on stackage issues around `resolv`.

**Comment by lyokha** [comment]
@andreasabel Should I register at Stackage for this?

**Comment by lyokha** [comment]
@andreasabel it looks that the #17 is not present in the build. See https://hackage.haskell.org/package/resolv-0.2.0.0/reports/1. Probably, we need somehow trigger autoreconf at hackage builder for this.

**Comment by lyokha** [comment]
@andreasabel , it seems that it is not a Hackage issue, perhaps you forgot to `autoreconf -i` before making dist and the configure shipped with the package  did not test for `netdb` and `h_errno`. In the log, line `checking for struct __res_state.res_h_errno... yes` is absent. Would you re-upload the fix in `0.2.0.1`?

**Comment by andreasabel** [comment]
Oops, wasn't aware of the `autoreconf` step.  This is easy to blunder (`configure` isn't version-controlled, and `cabal` doesn't automatically run `autoreconf` either).
Candidate: https://hackage.haskell.org/package/resolv-0.2.0.1/candidate

**Comment by andreasabel** [comment]
Published: https://hackage.haskell.org/package/resolv-0.2.0.1

**Comment by andreasabel** [comment]
> @andreasabel Should I register at Stackage for this?

It is enough to make a PR against https://github.com/commercialhaskell/stackage/ with changes to the `build-constraints.yaml` file.

**Comment by lyokha** [comment]
This one is good: https://hackage.haskell.org/package/resolv-0.2.0.1/candidate/src/configure: it contains lines with `netdb`

```
ac_fn_check_decl "$LINENO" "h_errno" "ac_cv_have_decl_h_errno" "
#include <netdb.h>

" "$ac_c_undeclared_builtin_options" "CFLAGS"
```

**Comment by andreasabel** [comment]
> it looks that the #17 is not present in the build.

It would be good to have a test that ensures such things.  I do `cabal test` before uploading, this could catch oversights...

**Comment by andreasabel** [comment]
I deprecated 0.2.0.0 on hackage to indicate that this is not a good release.

**Comment by lyokha** [comment]
> Oops, wasn't aware of the `autoreconf` step. This is easy to blunder (`configure` isn't version-controlled, and `cabal` doesn't automatically run `autoreconf` either). Candidate: https://hackage.haskell.org/package/resolv-0.2.0.1/candidate

Yes, I did not keep in mind this as well, just guessed what happened.

**Comment by lyokha** [comment]
> I deprecated 0.2.0.0 on hackage to indicate that this is not a good release.

Strictly speaking, `0.2.0.0` wasn't bad, it just did not provide what it claimed in the changelog.

**Comment by andreasabel** [comment]
I added release instructions: https://github.com/haskell-hvr/resolv/blob/7c26271f84a33298df9a42841536da71873291ed/DEVELOPER.md?plain=1#L4-L7

**Comment by lyokha** [comment]
Hurray!

```ShellSession
$ ghci
GHCi, version 9.6.1: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/lyokha/.ghci
Prelude> import Network.DNS 
Prelude Network.DNS> :set -XOverloadedStrings 
Prelude Network.DNS> queryA $ Name "www.ayyayagoogle.com"
*** Exception: DnsHostNotFound
Prelude Network.DNS> 
```

Memory leaks have gone as well.

**Comment by andreasabel** [comment]
Congrats, this issue is resolved to full satisfaction!
