### ISSUE TITLE
Add tags (and maybe releases) to indicate the hackage version

### ISSUE THREAD

**Issue by adetokunbo** [haskell-hvr/resolv#2]
It'd be nice to checkout the precise commits of this repo that correspond to the uploaded hackage versions of the package.

One way to do this would be tag the commits that were released to hackage, and maybe even create [GitHub releases](https://help.github.com/articles/creating-releases/) for them.

**Comment by hvr** [comment]
Thanks for the reminder; I actually had some releases tagged locally and just forgot to push them; now I have, see

https://github.com/haskell-hvr/resolv/releases
